# Generated by Django 5.0.3 on 2024-04-05 19:04

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0020_delete_calendaritem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('start', models.DateTimeField(default=django.utils.timezone.now, validators=[django.core.validators.MinValueValidator(datetime.datetime(2024, 4, 5, 18, 4, 30, 675026, tzinfo=datetime.timezone.utc))], verbose_name='Начало')),
                ('end', models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.datetime(2024, 5, 3, 19, 4, 30, 675026, tzinfo=datetime.timezone.utc))], verbose_name='Конец')),
                ('notification', models.DateTimeField(blank=True, null=True, verbose_name='Дата уведомления')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание')),
                ('icon', models.CharField(blank=True, choices=[('birthday', 'День рождения'), ('wedding', 'Свадьба'), ('other', 'Другое')], max_length=100, null=True, verbose_name='Иконка')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userprofile', verbose_name='Создатель')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.family', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Событие календаря',
                'verbose_name_plural': 'События календаря',
            },
        ),
    ]
