# Generated by Django 5.0.2 on 2024-04-05 19:49

import datetime
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightlist_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendaritem',
            name='end',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.datetime(2024, 5, 3, 19, 49, 55, 410560, tzinfo=datetime.timezone.utc))], verbose_name='Конец'),
        ),
        migrations.AlterField(
            model_name='calendaritem',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[django.core.validators.MinValueValidator(datetime.datetime(2024, 4, 5, 18, 49, 55, 410560, tzinfo=datetime.timezone.utc))], verbose_name='Начало'),
        ),
    ]
