# Generated by Django 5.0.3 on 2024-04-17 18:23

import datetime
import django.core.validators
import django.utils.timezone
import lightlist_calendar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightlist_calendar', '0002_alter_calendaritem_end_alter_calendaritem_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendaritem',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 17, 18, 23, 37, 845718, tzinfo=datetime.timezone.utc), validators=[django.core.validators.MaxValueValidator(lightlist_calendar.models.time_end)], verbose_name='Конец'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calendaritem',
            name='icon',
            field=models.CharField(blank=True, choices=[('work', 'Другое'), ('directions_walk', 'Прогулка'), ('apartment', 'Работа'), ('holiday_village', 'Дача'), ('celebration', 'День рождения'), ('park', 'Новый год'), ('favorite', 'День святого валентина'), ('woman', '8 Марта'), ('military_tech', '23 Февраля'), ('partner_exchange', 'Свадьба')], max_length=100, null=True, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='calendaritem',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[django.core.validators.MinValueValidator(lightlist_calendar.models.time_start)], verbose_name='Начало'),
        ),
    ]
