# Generated by Django 5.0.3 on 2024-04-05 18:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0017_alter_calendaritem_end_alter_calendaritem_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductListComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('unit', models.CharField(choices=[('шт', 'шт'), ('кг', 'кг'), ('мл', 'мл')], max_length=2, verbose_name='Мера измерения')),
                ('amount', models.FloatField(verbose_name='Количество')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.family')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
