# Generated by Django 5.0.2 on 2024-03-09 12:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_userprofile_options_family_userprofile_family'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='family',
        ),
        migrations.AddField(
            model_name='family',
            name='familyAvatar',
            field=models.ImageField(blank=True, null=True, upload_to='familyImg/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'])], verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='familyIdent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.family'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profileAvatar',
            field=models.ImageField(blank=True, null=True, upload_to='UserProfileImg', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg, png, ico'])]),
        ),
    ]
