# Generated by Django 5.0.2 on 2024-03-09 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_familyident_userprofile_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='familyAvatar',
            field=models.ImageField(blank=True, null=True, upload_to='familyImg/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'ico'])], verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profileAvatar',
            field=models.ImageField(blank=True, null=True, upload_to='UserProfileImg', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'ico'])]),
        ),
    ]
