# Generated by Django 5.0.3 on 2024-03-20 17:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_productlistcomponent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joinfamilyrequest',
            options={'verbose_name': 'Запрос', 'verbose_name_plural': 'Запросы'},
        ),
        migrations.AlterModelOptions(
            name='productlistcomponent',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.CreateModel(
            name='WishListComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('wish_picture', models.ImageField(blank=True, null=True, upload_to='wishImg/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'ico'])], verbose_name='Картинка')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('active', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, choices=[], max_length=100, null=True, verbose_name='Причина')),
                ('custom_reason', models.CharField(blank=True, max_length=100, null=True, verbose_name='Причина')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userprofile')),
            ],
            options={
                'verbose_name': 'Желание',
                'verbose_name_plural': 'Желания',
            },
        ),
    ]
