# Generated by Django 5.0.3 on 2024-03-27 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_userprofile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloudfile',
            name='file',
        ),
        migrations.AddField(
            model_name='cloudfile',
            name='archive_file',
            field=models.FileField(blank=True, null=True, upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'rar', '7z', 'tar', 'gz'])]),
        ),
        migrations.AddField(
            model_name='cloudfile',
            name='doc_file',
            field=models.FileField(blank=True, null=True, upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf', 'odt', 'rtf', 'txt', 'ppt', 'pptx', 'xls', 'xlsx'])]),
        ),
        migrations.AddField(
            model_name='cloudfile',
            name='photo_file',
            field=models.FileField(blank=True, null=True, upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'ico', 'jpeg', 'bmp'])]),
        ),
        migrations.AddField(
            model_name='cloudfile',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mkv', 'mov', 'webm', 'avi'])]),
        ),
    ]
