# Generated by Django 5.0.3 on 2024-03-30 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_cloudfile_file_cloudfile_archive_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloudfile',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.CreateModel(
            name='CalendarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('notification', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userprofile', verbose_name='Создатель')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.family', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Событие календаря',
                'verbose_name_plural': 'События календаря',
            },
        ),
    ]
