# Generated by Django 5.0.3 on 2024-04-05 18:13

import datetime
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_calendaritem_description_calendaritem_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendaritem',
            name='end',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.datetime(2024, 5, 3, 18, 13, 33, 547857, tzinfo=datetime.timezone.utc))], verbose_name='Конец'),
        ),
        migrations.AlterField(
            model_name='calendaritem',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[django.core.validators.MinValueValidator(datetime.datetime(2024, 4, 5, 17, 13, 33, 547857, tzinfo=datetime.timezone.utc))], verbose_name='Начало'),
        ),
    ]
