# Generated by Django 5.0.3 on 2024-04-05 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_calendaritem_end_alter_calendaritem_start_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalendarItem',
        ),
    ]
