# Generated by Django 5.0.2 on 2024-05-11 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_delete_calendaritem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='familyAvatar',
            field=models.ImageField(blank=True, null=True, upload_to='familyImg/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'ico', 'jpeg', 'webp'])], verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='family',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Название'),
        ),
    ]
