# Generated by Django 5.0.3 on 2024-04-05 18:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0018_alter_calendaritem_end_alter_calendaritem_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishListComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('wish_picture', models.ImageField(blank=True, null=True, upload_to='wishImg/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'ico'])], verbose_name='Картинка')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('active', models.BooleanField(default=True)),
                ('reason', models.CharField(choices=[('нг', 'Новый год'), ('св', 'Свадьба'), ('др', 'День Рождения'), ('wd', '8 Марта'), ('md', '23 Февраля'), ('др', 'Другое')], default='другое', max_length=100, null=True, verbose_name='Причина')),
                ('custom_reason', models.CharField(blank=True, max_length=100, null=True, verbose_name='Своя причина')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userprofile')),
            ],
            options={
                'verbose_name': 'Желание',
                'verbose_name_plural': 'Желания',
            },
        ),
    ]
