# Generated by Django 5.0.2 on 2024-05-11 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudfile',
            name='photo_file',
            field=models.FileField(blank=True, null=True, upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'ico', 'jpeg', 'bmp', 'webp'])]),
        ),
    ]
